#!/bin/bash

RESULT=`cargo fmt -- --check`

if [[ ! -z "$RESULT" ]]; then
    cargo fmt
    echo -e "\e[1;37m-- please add new changes and retry commit --\e[0m"
    echo -e "\e[31m  info\e[0m: commit creation aborted"
    echo -e "\e[34mreason\e[0m: code is not formatted"
    echo -e "\e[32m apply\e[0m: 'cargo fmt' in automatic mode"
    exit 1
fi